"""Initial migration

Revision ID: 5726bb4cdcd3
Revises:
Create Date: 2026-02-16 21:38:58.422231

"""

import sqlalchemy as sa
from alembic import op

from url_checker.helpers.custom_types import UTCDateTime

# revision identifiers, used by Alembic.
revision = "5726bb4cdcd3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized", sa.Text(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("last_completed_analysis_id", sa.Integer(), nullable=True),
        sa.Column(
            "last_completed_analysis_utc", UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("analysis_in_progress", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=False),
        sa.Column("date_modified_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "analyses",
        sa.Column("datetime_utc", UTCDateTime(timezone=True), nullable=True),
        sa.Column("url_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=False),
        sa.Column("date_modified_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["urls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("start_utc", UTCDateTime(timezone=True), nullable=True),
        sa.Column("end_utc", UTCDateTime(timezone=True), nullable=True),
        sa.Column("error_logs", sa.Text(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("type_code", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=False),
        sa.Column("date_modified_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "results",
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("validity_status", sa.String(length=16), nullable=False),
        sa.Column("reachability_status", sa.String(length=16), nullable=False),
        sa.Column("security_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=False),
        sa.Column("date_modified_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("results")
    op.drop_table("jobs")
    op.drop_table("analyses")
    op.drop_table("urls")
    # ### end Alembic commands ###
