"""empty message

Revision ID: cb6cbdb64251
Revises: c95bf06f0fac
Create Date: 2026-04-23 11:33:09.851027

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cb6cbdb64251"
down_revision = "c95bf06f0fac"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("synthesis", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("raw_error", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("raw_output", sa.Text(), nullable=False))
        batch_op.alter_column(
            "validity_status", existing_type=mysql.VARCHAR(length=16), nullable=True
        )
        batch_op.alter_column(
            "reachability_status", existing_type=mysql.VARCHAR(length=16), nullable=True
        )
        batch_op.alter_column(
            "security_status", existing_type=mysql.VARCHAR(length=16), nullable=True
        )
        batch_op.drop_column("output")

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("output", mysql.TEXT(), nullable=False))
        batch_op.alter_column(
            "security_status", existing_type=mysql.VARCHAR(length=16), nullable=False
        )
        batch_op.alter_column(
            "reachability_status",
            existing_type=mysql.VARCHAR(length=16),
            nullable=False,
        )
        batch_op.alter_column(
            "validity_status", existing_type=mysql.VARCHAR(length=16), nullable=False
        )
        batch_op.drop_column("raw_output")
        batch_op.drop_column("raw_error")
        batch_op.drop_column("synthesis")

    # ### end Alembic commands ###
